sudo: false
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script: node_modules/karma/bin/karma start karma.conf.js --single-run
branches:
  only:
  - master
  - v5
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
